version: "3.9"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - "8448:8448"
    networks:
      - jackbox

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "8447:80"
    networks:
      - jackbox

networks:
  jackbox:
    name: jackbox
    driver: bridge